databases:
  - name: multilang_site_db
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: multilang_site
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn multilang_site.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: multilang_site_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
