services:
  - type: web
    name: multilang-site
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: multilang_site.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromFile:
          path: db.sqlite3

databases:
  - name: multilang-site-db
    type: sqlite
    plan: hobby
    defaultDatabaseName: db.sqlite3