services:
- type: web
  name: multilang_site
  runtime: python
  repo: https://github.com/MassiTgh/Multilang_site
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python -m gunicorn src.multilang_site.asgi:application -k uvicorn.workers.UvicornWorker
version: "1"
